### PR TITLE
Fix heroku deploy button

### LINKED ISSUE #8: The content of app.json is not a valid JSON object.
I get the following error message when I click the "deploy to heroku" button:
> The content of app.json is not a valid JSON object.

 I have never used heroic before, but just created an account.

screen shot 2016-01-10 at 7 21 08 pm

### PR DESCRIPTION
**Pull request by zbeekman**
Fixes #8

### CODE REVIEW

**Comment by parkr** [comment]
LGTM!

**Comment by zbeekman** [comment]
First time I've encountered that one... LGTM ==> "Looks good to me"? not sure why the PR test fails, but that's not my problem.

**Comment by parkr** [comment]
@zbeekman, yep!! Haha :)

**Comment by zbeekman** [comment]
I'm not sure what the issue is with the Travis-CI build, but it seems that my heroku instance isn't able to perform the conversion--perhaps the two are related:

https://github-pdf.herokuapp.com/benbalter/markdown-to-pdf/blob/master/README.pdf :heavy_check_mark: 

https://md-to-pdf.herokuapp.com/benbalter/markdown-to-pdf/blob/master/README.pdf :heavy_multiplication_x:

**Comment by benbalter** [comment]
Failing test seems unrelated. Thanks @zbeekman!

**Comment by benbalter** [comment]
> I'm not sure what the issue is with the Travis-CI build, but it seems that my heroku instance isn't able to perform the conversion--perhaps the two are related:

The issue had to be with the demo running on an older instance. Upgraded and confirmed `master` now runs on Ceder-14 (latest).

**Pull request merged**
